### ISSUE TITLE
Regarding HEAAN library

### ISSUE THREAD

**Issue by trajore** [corelab-src/dacapo#3]
can we use the publicly available version of the HEAAN library to test this,
what is the procedure to do so? does the published version of code have all the dependencies for this or something more is required?

the version I am referring to : https://hub.docker.com/r/cryptolabinc/heaan

Thanks

**Comment by Seonyoung-Cheon** [comment]
We received the source code from Cryptolab and used a modified version for our experiments. 
So, it is not compatible with the publicly available version of HEaaN. 
We apologize for not being able to share it due to licensing issues.
We are currently conducting additional research on this matter.

Thank you!
